= Changelog

This document provides a high-level view of the changes introduced in Kotlin Data Model Processor by release.
For an even more detailed look at what has changed, refer to the {uri-repo}/commits/master[commit history].

This project utilizes semantic versioning.

== Next version 1.2.0 (TBD)

New features and improvements:

* New `ImplementModel` annotation argument: `templateSuffix`, defaults to `Template`.
* Immutable `ObjectModel` interface is now generated from `ObjectTemplate` interface.
* `Comparable` implementation, see xref:model-annotations/src/main/kotlin/net/eraga/tools/models/ImplementComparable.kt[ImplementComparable] Annotation
* Option to completely disable default class generation (and DSL initializer).
* Option to generate abstract class (with no DSL initializer).
//* `hashCode` / `equals` implementations, see xref:model-annotations/src/main/kotlin/net/eraga/tools/models/ImplementHashCode.kt[ImplementHashCode] Annotation and xref:model-annotations/src/main/kotlin/net/eraga/tools/models/ImplementEquals.kt[ImplementEquals] Annotation
//TODO: * Boilerplate DTO classes
//TODO: * Boilerplate classes for Spring Controller/Service/Repository in conjunction with DTO


== 1.1.0 (2021.07.12)

New features and improvements:

* Support nested inheritance.
* `ConstructorInitializer` annotation allows to use custom constructor initializers.
* `PreventOverride` annotation allows to mark certain properties of interface to be excluded from model implementations.
* Better type handling of kotlin classes.
