= Changelog

This document provides a high-level view of the changes introduced in Kotlin Data Model Processor by release.
For an even more detailed look at what has changed, refer to the {uri-repo}/commits/master[commit history].

This project utilizes semantic versioning.

== Next version 2.1.0 (TBD)

New features and improvements:

* Nested arrays support in property definitions, e.g. `val array = Array<Array<Int>`
* Nested generics in type definitions support, e.g. `interface SomeModel : List<List<Int>>`

== Version 2.0.0 (TBA)

New features and improvements:

* Completely reworked API
** Generator annotations:
*** `Implement.Immutable` for immutables that inherit from model
*** `Implement.DTO` for immutables that don't inherit from model to be used as Data Transfer Objects
//TODO:
*** `Implement.JPAEntity`
** Property annotations:
*** `Implement.Omit(in = "ImplementationName")` will remove certain property from `ImplementationName`
*** `Implement.Init(with = "")`


== Version 1.2.0 (2021.07.17)

New features and improvements:

* New `ImplementationSettings` annotation arguments: `templateSuffix`, defaults to `Template`.
* Immutable `ObjectModel` interface can be generated either from `ObjectTemplate` interface or skipped so Template itself can be ImmutableModel.
* xref:model-annotations/src/main/kotlin/net/eraga/tools/models/GeneratedClass.kt[GeneratedClass] hints processor about properties of types that are generated from Template but not inherited from it.
* `Comparable` implementation, see xref:model-annotations/src/main/kotlin/net/eraga/tools/models/ImplementComparable.kt[ImplementComparable] Annotation
* Option to completely disable default class (and DSL initializer) generation.
* Option to generate abstract class (with no DSL initializer).
* `hashCode` / `equals` implementations, see xref:model-annotations/src/main/kotlin/net/eraga/tools/models/ImplementHashCode.kt[ImplementHashCode] Annotation and xref:model-annotations/src/main/kotlin/net/eraga/tools/models/ImplementEquals.kt[ImplementEquals] Annotation to overcome xref:https://blog.jetbrains.com/kotlin/2015/09/feedback-request-limitations-on-data-classes/[Limitations on Data Classes]
* Basic support of TypeScript data model generation by partial rewriting of xref:https://github.com/ntrrgc/ts-generator[ts-generator] to make it work on top of kotlinpoet.
* Generate multiple implementations with annotation xref:model-annotations/src/main/kotlin/net/eraga/tools/models/Implementations.kt[Implementations].
* Enforce to use named arguments in implementation class constructors, setting is ignored for data classes.
//* TODO: Generate class to class convertors
//* TODO: generate toString
//* TODO: generate deepCopy
//* TODO: Inherit annotations (select by package wildcard)
//TODO: * Boilerplate classes for Spring Controller/Service/Repository in conjunction with DTO


== 1.1.0 (2021.07.12)

New features and improvements:

* Support nested inheritance.
* `ConstructorInitializer` annotation allows to use custom constructor initializers.
* `PreventOverride` annotation allows to mark certain properties of interface to be excluded from model implementations.
* Better type handling of kotlin classes.
